### PR TITLE
Feature/workshop manager updates

### PR DESCRIPTION
**Pull request by mikeymike**
@AydinHassan probably not ready to just go straight in... I suspect we may need to add some more copy to the home page, not sure though. 

I did put some code in for a video but commented it out for now as I couldn't get it looking right, you can uncomment it to take a look at what I was thinking of. 

The header phrases on the homepage could probably do with tweaking, I just chucked some in there to start off with.

### CODE REVIEW

**Comment by AydinHassan** [comment]
@mikeymike I've added some more info and tweaked the homepage a little now, could you check it out and see if you think we have all the information necessary?

I think the final stage is to get @OliverChenery to check it out, because I've probably made it look worse :D

**Comment by mikeymike** [comment]
@AydinHassan I like it dude. I don't think we need the `Get Started` button... I dno just looks repetitive to me and the intro text (What is PHP School) looks a little odd, maybe it's the spacing around it I'm not sure @OliverChenery what do you think ? ... in fact I just increased the width of the getting started block and apart from the spacing between it I think it ties it in a little better. 

screen shot 2016-08-17 at 07 58 22

**Comment by mikeymike** [comment]
@AydinHassan was the title color change on installation and docs intentional ? ... seems a little inconsistent with the other pages... also just noticed the submit a workshop has the logo on it, you think it's worth putting on all headers (just thinking about consistency again)

**Comment by AydinHassan** [comment]
@mikeymike didn't mean to change the colours of the titles :o. I kinda like the logo on all the headers tbh, so I think yeah.

I gave up on the styling for the homepage as Oli said he would take a look :D

**Pull request merged**
